---
- name: "Template i3 config"
  include_role:
    name: dotfiles-role-generic-template
  vars:
    template_root: "{{ config_dir }}"
    template_path: "{{ item }}"
  with_items:
    - i3/config
    - i3status/config
